version: "2"
linters:
  enable:
    - forbidigo
    - gosec
    - nilerr
    - predeclared
    - reassign
    - sqlclosecheck
    - unconvert
  disable:
    - staticcheck
  settings:
    forbidigo:
      forbid:
        - pattern: fmt\.Print*
        - pattern: spew.Dump
    gosec:
      excludes:
        - G601
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
